name: Release Master

on: [workflow_dispatch, push]


jobs:
  master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout web-yuedu3 Project
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Checkout web-yuedu3 Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: slave
          path: slave
          
      - name: Build Master
        working-directory: master
        run: |
          npm install
          npm run-script build
          zip -q -r master_dist.zip ./dist

      - name: Set Env
        shell: bash
        run: |
          version="v$(date -d "8 hour" -u +3.%y.%m%d%H%M)"
          echo "APP_VER=$version" >> $GITHUB_ENV
          tag_name=$(curl -s https://api.github.com/repos/gedoor/legado_web_bookshelf/releases/latest|jq .tag_name -r)
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
          
      - name: Create Release
        if: ${{ env.TAG_NAME != env.APP_VER }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_VER }}
          release_name: ${{ env.APP_VER }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Master
        if: ${{ env.TAG_NAME != env.APP_VER }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/master/master_dist.zip
          asset_name: master_${{ env.APP_VER }}.zip
          asset_content_type: application/octet-stream

      - name: Upload Master
        if: ${{ env.TAG_NAME == env.APP_VER }}
        uses: actions/upload-artifact@v2
        with:
          name: master_${{ env.APP_VER }}
          path: ${{ github.workspace }}/master/dist
          if-no-files-found: error

      - name: Push changes to legado
        if: ${{ github.actor == 'gedoor' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone "https://${{ github.actor }}:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.actor }}/legado" --depth 1
          rm -rf legado/app/src/main/assets/web/bookshelf/*
          mv -f $GITHUB_WORKSPACE/master/dist/* legado/app/src/main/assets/web/bookshelf/
          cd legado
          git commit -a -m "web bookshelf: ${{ env.APP_VER }}"
          git push
